Fixing artifact failure

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -26,10 +26,11 @@ jobs:
         run: npx playwright install
 
       - name: Run Playwright tests
-        run: npx playwright test
+        run: npx playwright test || true  # prevents job fail before report
 
       - name: Upload Playwright Report
-        uses: actions/upload-artifact@v3
+        if: always()                      # upload even if tests fail
+        uses: actions/upload-artifact@v4
         with:
           name: playwright-report
           path: playwright-report/
